version: '3'

services:

  mysql_ssab:
    container_name: mysql_ssab
    image: mysql:8
    restart: always
    healthcheck: 
      test: ['CMD', 'mysqladmin', 'ping', '--silent']
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s
    networks: 
      - directus_ssab
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}

  adminer_ssab:
    container_name: adminer_ssab
    image: adminer:latest
    restart: always
    depends_on:
      - mysql_ssab
    networks: 
      - directus_ssab
    environment:
      ADMINER_DEFAULT_SERVER: mysql_ssab
    ports:
      - 8080:8080

  cache_ssab:
    container_name: cache_ssab
    image: redis:6
    networks:
      - directus_ssab

  directus_ssab:
    container_name: directus_ssab
    image: directus/directus:10.0.0
    restart: always
    ports:
      - ${DIRECTUS_PORT}:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./snapshots:/directus/snapshots
    networks:
      - directus_ssab
    depends_on:
      - cache_ssab
      - mysql_ssab
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'mysql'
      DB_HOST: 'mysql_ssab'
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASS}
      DB_DATABASE: ${MYSQL_DB}
      DB_PORT: '3306'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache_ssab:6379'
      CACHE_AUTO_PURGE: 'true'
      CACHE_SYSTEM_TTL: '2m'
      CACHE_SCHEMA: 'false'
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true'

      PUBLIC_URL: ${PUBLIC_URL}

  graphiql_ssab:
    container_name: graphiql_ssab
    image: plutoz/graphiql
    depends_on:
      - directus_ssab
    ports:
      - 4000:4000
    environment:
      API_ENDPOINT: ${API_ENDPOINT}
    networks:
      - directus_ssab

networks:
  directus_ssab:
    driver: bridge