name: deploy-remote
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      version:
        description: 'App version'
        required: false
jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Pull Latest
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            git pull
            touch .env
            cat << EOF > .env 
            ${{ secrets.ENV_FILE }} 
            EOF
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            # npm run stop
            # npm run start